dave1/config/routes.rb
Rails.application.routes.draw do
  
  
  resources :movies
  
  get 'people/index'

  #get 'page/home'
  get 'home' => 'page#home'

  #get 'page/about_us'
  get 'about_us' => 'page#about_us'

  # get 'contact_us' =>'page#contact_us'
  # post 'contact_us' =>'page#contact_us'
  
  match 'contact_us'=>'page#contact_us', :via => [:post, :get]

  # get 'products' =>'page#products' WE are getting rid of this b/c resources :products (from db:migrate)

  get 'newsletter' =>'page#newsletter'

  get 'blog' => 'page#blog'
  
  get 'calendar(/:year(/:month))' => 'page#calendar', :as => 'calendar'

  get 'calendar' => 'page#calendar'

  get 'articles' => 'page#articles'

  get 'login' => 'page#login'

  get 'dave/teach'

  get 'dave/speak'

  get 'dave/dig'

  # you could have 'say/dacks(the outside world's URL) go to => say#hello'
  get 'say/hello' => 'say#hello'
  get 'say/goodbye'
  get 'say/something'
  
  root 'page#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

dave1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dave1/app/models/movie.rb
class Movie < ApplicationRecord
    validates_presence_of :name, :director
    validates_numericality_of :year, :length, :greater_than => 0
    validates_uniqueness_of :name, :message => "is already used, dummy!"
    validates_length_of :format, :maximum => 5, minimum:2

    def proper_name
        name.titleize
    end
end

dave1/app/models/person.rb
class Person < ApplicationRecord
    def full_name
       return first_name + " " + last_name 
    end
end

dave1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

dave1/app/controllers/dave_controller.rb
class DaveController < ApplicationController
  def teach
  end

  def speak
  end

  def dig
  end
end

dave1/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @page = params['page'].to_i
    @movies = Movie.limit(5).offset(@page*5)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :director, :description, :year, :length, :format, :image, :thumbnail)
    end
end

dave1/app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about_us
  end

  def contact_us
    @submitted  = params["commit"]
    @form_error = false
    @name = params["name"]
    if @name == ""
      flash.now['error'] = "Must enter your name!"
      @form_error = true
    end
    @email = params["email"]
    @question = params["question"]
  end

  def products
  end

  def newsletter
  end

  def blog
  end

  def calendar
    @time = Time.now
    @month = params['month'].to_i
    @year = params['year'].to_i
    if ( !(@month >= 1 && @month <= 12))
      @month = @time.strftime("%m").to_i
    end
    if (@year <= 0)
      @year = @time.strftime("%Y").to_i
    end
  end

  def articles
  end

  def login
  end
end

dave1/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end
end

dave1/app/controllers/say_controller.rb
class SayController < ApplicationController
  # SayController inherits from ("<") the class ApplicationConroller
  def hello
    @yo = "yo ho!"
    @now = Time.now
  end
  
  def goodbye
  end
  
  def something
  end
  
end

dave1/app/helpers/application_helper.rb
module ApplicationHelper
    def nav_link_to ( click_text, action, url, style )
        if action_name == action
           return link_to click_text, url, :class => style
        else
            return link_to click_text, url
        end
    end
    
    
end

dave1/app/helpers/dave_helper.rb
module DaveHelper
end

dave1/app/helpers/movies_helper.rb
module MoviesHelper
end

dave1/app/helpers/page_helper.rb
module PageHelper
    
    def calendar(month, year)
        current_date = Date.new(year, month, 1)
        
        prev_month = month - 1
        prev_year = year
        next_year = year
        next_month = month + 1
        
        if( prev_month <= 0)
           prev_month = 12
           prev_year = year - 1
        end
        
        if(next_month > 12)
            next_month = 1
            next_year = year + 1
        end
        
        cal = current_date.strftime("%B") # "/page/calendar?month=#{prev_month}&year=#{prev_year}"
        cal += link_to "Prev", calendar_path(:month=>prev_month, :year=>prev_year)
        day_of_week = current_date.strftime("%w").to_i #"/page/calendar?month=#{next_month}&year=#{next_year}"
        cal += link_to "Next", calendar_path(:month=>next_month, :year=>next_year)
        cal  += "<table border = '1'><tr>"
        days = %w(Sun Mon Tue Wed Thu Fri Sat)
        days.each do | day |
            cal += "<td>#{day}</td>"
        end
        # Second row - first week of the month
            cal += "<tr>"
        day_of_week.times do |day|
           cal += "<td>&nbsp;</td>"
        end
        
        # Print the days of week starting with 1
        (7 - day_of_week).times do |day|
            cal += "<td>#{day + 1}</td>"
        end
        
        #loop to do in between rows
        
        #loop to do last r
        
        cal += "</tr>"
        cal += "</tr></table>"
        cal += "Month: #{month} <br/>Year: #{year}<br/>"
        cal += "Day: #{current_date}<br/>"
        cal += day_of_week.to_s
        return cal 
        
    end
    
end

dave1/app/helpers/people_helper.rb
module PeopleHelper
end

dave1/app/helpers/say_helper.rb
module SayHelper
end

dave1/app/views/dave/dig.html.erb
<h1>Dave#dig</h1>
<p>Find me in app/views/dave/dig.html.erb</p>

dave1/app/views/dave/speak.html.erb
<h1>Dave#speak</h1>
<p>Find me in app/views/dave/speak.html.erb</p>

dave1/app/views/dave/teach.html.erb
<h1>Dave#teach</h1>
<p>Find me in app/views/dave/teach.html.erb</p>

dave1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Dave1</title>
   
  
    
    <%= csrf_meta_tags %>
    <!--Rails has a special way of including stylehseets ('application.css/.js' tells it where to get the stylsheets from)-->
    <%= stylesheet_link_tag    'application', media: 'screen', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'print', media: 'print', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  	
  	
  
  </head>

  <body>
    
    <div id="wrapper"><!-- #wrapper -->

	<header><!-- header -->
		<h1><a href="#">Cowboy Up</a></h1>
		<h2>Where the buffalo roam</h2>
		<%= image_tag "cowboyup.jpg", size: "940x200" %>
		<!--<img src="images/cowboyup.jpg" width="940" height="200" alt=""><!-- header image -->
	</header><!-- end of header -->
	
<!--this is a lot like a 'yield', it's saying render this partial called _nav -->
<%= render :partial => 'shared/nav' %>

	<section id="main"><!-- #main content and sidebar area -->
		<section id="container"><!-- #container -->
			<section id="content"><!-- #content -->
    
    <!--everything in the view (sayhello) gets put in 'yield'-->
    <%= yield %>
    
						
    		</section><!-- end of #content -->
    		</section><!-- end of #container -->
    		<aside id="sidebar"><!-- sidebar -->
    				<h3>Things To Do</h3>
    					<ul>
    						<li><a href="#">Play Games</a></li>
    						<li><a href="#">Chat With Friends</a></li>
    						<li><a href="#">Swap Stories</a></li>
    						<li><a href="#">Sell Stuff</a></li>
    						<li><a href="#">Buy Stuff</a></li>
    						<li><a href="#">Trade Stuff</a></li>
    					</ul>
    					
    				<h3>Our Sponsors</h3>
    				  <%= image_tag "ad125.jpg" %>
    				  <%= image_tag "ad125.jpg" %>
    					<!--<img src="images/ad125.jpg" alt="" /> <img src="images/ad125.jpg" alt="" /><br />-->
    					<!--<img src="images/ad125.jpg" alt="" /> <img src="images/ad125.jpg" alt="" /><br /><br />-->
    
    				<h3>Connect With Us</h3>
    					<ul>
    						<li><a href="#">Twitter</a></li>
    						<li><a href="#">Facebook</a></li>
    					</ul>
    
    		</aside><!-- end of sidebar -->
    
    	</section><!-- end of #main content and sidebar-->
    
    	<footer>
    		<section id="footer-area">
    
    			<section id="footer-outer-block">
    					<aside id="first" class="footer-segment">
    							<h3>Blogroll</h3>
    								<ul>
    									<li><a href="#">one linkylink</a></li>
    									<li><a href="#">two linkylinks</a></li>
    									<li><a href="#">three linkylinks</a></li>
    									<li><a href="#">four linkylinks</a></li>
    									<li><a href="#">five linkylinks</a></li>
    								</ul>
    					</aside><!-- end of #first footer segment -->
    
    					<aside id="second" class="footer-segment">
    							<h3>Awesome Stuff</h3>
    								<ul>
    									<li><a href="#">one linkylink</a></li>
    									<li><a href="#">two linkylinks</a></li>
    									<li><a href="#">three linkylinks</a></li>
    									<li><a href="#">four linkylinks</a></li>
    									<li><a href="#">five linkylinks</a></li>
    								</ul>
    					</aside><!-- end of #second footer segment -->
    
    					<aside id="third" class="footer-segment">
    							<h3>Coolness</h3>
    								<ul>
    									<li><a href="#">one linkylink</a></li>
    									<li><a href="#">two linkylinks</a></li>
    									<li><a href="#">three linkylinks</a></li>
    									<li><a href="#">four linkylinks</a></li>
    									<li><a href="#">five linkylinks</a></li>
    								</ul>
    					</aside><!-- end of #third footer segment -->
    					
    					<aside id="fourth" class="footer-segment">
    							<h3>Blahdyblah</h3>
    								<p>Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
    					</aside><!-- end of #fourth footer segment -->
    
    			</section><!-- end of #footer-outer-block -->
    
    		</section><!-- end of #footer-area -->
    	</footer>
    
    </div><!-- #wrapper -->
    <!-- Free template created by http://freehtml5templates.com -->
  </body>
</html>

dave1/app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :director %>
    <%= f.text_field :director %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <div class="field">
    <%= f.label :length %>
    <%= f.text_field :length %>
  </div>

  <div class="field">
    <%= f.label :format %>
    <%= f.text_field :format %>
  </div>
  
  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :thumbnail %>
    <%= f.text_field :thumbnail %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dave1/app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

dave1/app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<%= link_to "Prev", movies_path(page:@page-1) %>
<%= link_to "Next", movies_path(page:@page+1) %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Director</th>
      <th>Description</th>
      <th>Year</th>
      <th>Length</th>
      <th>Format</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%=movie.id%></td>
        <td><%= link_to movie.proper_name, movie_path(movie) %></td>
        <td><%= movie.director %></td>
        <td><%= truncate(movie.description.html_safe, length: 20) %></td>
        <td><%= movie.year %></td>
        <td><%= movie.length %></td>
        <td><%= movie.format %></td>
        <td><%= movie.thumbnail%></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

dave1/app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

dave1/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.proper_name %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description.html_safe %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length %>
</p>

<p>
  <strong>Format:</strong>
  <%= @movie.format %>
</p>

<p>
  <strong>Image:</strong>
  <% if @movie.image %>
    <%= image_tag @movie.image %>
  <% end %>
    
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

dave1/app/views/page/about_us.html.erb
<h1>Page#about_us</h1>
<p>Find me in app/views/page/about_us.html.erb</p>

dave1/app/views/page/articles.html.erb
<h1>Page#articles</h1>
<p>Find me in app/views/page/articles.html.erb</p>

dave1/app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

dave1/app/views/page/calendar.html.erb
<h1>Calendar</h1>

<%= calendar(@month, @year).html_safe %>

dave1/app/views/page/contact_us.html.erb
<h1>Contact Us</h1>


Your name is <%= @name %><br/>
Your e-mail is <%= @email %><br/>

<% if flash['error'] %>
    <div class='error'><%= flash['error'] %></div>
<% end %>

<!--<pre>-->
<% params.each do |key, value| #DEBUGGING ONLY!! %>
<!--    <%= key + " ==> " + value %>-->
<!--<% end %>-->
<!--</pre>-->

<% if !@submitted || @form_error %>
    <br/>
    <%= form_for contact_us_path, :method => "POST" do %>
        <%= label_tag :name, "Enter your full name: " %>
        <%= text_field_tag :name, @name, placeholder: "Enter your name" %><br/>
        <%= label_tag :email, "Enter your e-mail address: " %>
        <%= email_field_tag :email, @email %><br/>
        <%= label_tag :question, "Enter your question: " %><br/>
        <%= text_area_tag :question, @question, size: "35x10" %><br/>
    
        <%= radio_button_tag :gender, "Male" %> Male <br/>
        <%= radio_button_tag :gender, "Female" %> Female <br/>
        <%= check_box_tag :newsletter, "newsletter", @newsletter %> Subscribe to my newsletter?<br/>
        <%= select_tag :product, options_for_select(
            [
                ['Skis', 1],
                ['Poles', 2],
                ['Boots', 3],
            ], 1) %>
        
    
    
        <%= submit_tag "Submit" %>
    
    <% end %>
<% else %>
    Thanks for your information.

<% end %>

dave1/app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

dave1/app/views/page/login.html.erb
<h1>Page#login</h1>
<p>Find me in app/views/page/login.html.erb</p>

dave1/app/views/page/newsletter.html.erb
<h1>Page#newsletter</h1>
<p>Find me in app/views/page/newsletter.html.erb</p>

dave1/app/views/page/products.html.erb
<h1>Page#products</h1>
<p>Find me in app/views/page/products.html.erb</p>

dave1/app/views/people/index.html.erb
<h1>People#index</h1>
<p>Find me in app/views/people/index.html.erb</p>
<% @people.each do |person| %>
    <%= person.full_name %><br/>
<% end %>

dave1/app/views/say/goodbye.html.erb
<h1>This is the goodbye view</h1>

dave1/app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>Find me in app/views/say/hello.html.erb</p>

Hello Dacks
<br/>
<%= 2+2 %>
<br/>
<% 3.times do%>
    HO!
    <h2><%= @yo %></h2>
    <p><%= @now %></p>
<% end %>
<br/>
<%= link_to "Teach Dave", dave_teach_path %>

dave1/app/views/say/something.html.erb
This is say something!

dave1/app/views/shared/_nav.html.erb
<nav> <!-- top nav -->
   <div class="menu">
      <ul>
         <li>
         	<%= nav_link_to "Home", "home", home_path, 'current_page' %></a></li>
         <li>
            <%= nav_link_to "About", 'about_us', about_us_path, 'current_page' %></a>
            <ul>
               <li><%=nav_link_to "Contact Us", 'contact_us', contact_us_path, 'current_page' %></li>
            </ul>
         </li>
         <li><%=link_to "Calendar", calendar_path %></li>
         <li>
            <%= link_to "Articles", articles_path %></a>
            <ul>
               <li><%=link_to "Newsletter", newsletter_path %></li>
            </ul>
         </li>
         <li><%=link_to "Blog", blog_path %></li>
         <li><%=link_to "Login", login_path %></li>
      </ul>
   </div>
</nav> <!-- end of top nav -->